services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: ichgram_be
    ports:
      - "3001:3001"
    # depends_on:
    #   - mongo
    volumes:
      - ./server/.env:/usr/src/app/.env

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: ichgram_fr
    ports:
      - "5173:5173"
    volumes:
      - ./client/.env:/app/.env
    # mongo-database:
    # container_name: mongo-database
    # image: mongo:7
    # restart: always
    # ports:
    #   - "27017:27017"
    # command: --auth --bind_ip 0.0.0.0
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
    #   MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    #   MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    # env_file:
    #   - .env
    # volumes:
    #   - ./data/db:/data/db
# volumes:
#   mongo-data: